// <auto-generated />
using System;
using Dispatch.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dispatch.Migrations
{
    [DbContext(typeof(HomeContext))]
    [Migration("20200128193004_FourthMigration")]
    partial class FourthMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Dispatch.Models.Assignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("Rescuer");

                    b.Property<int?>("RiderAssignedRescuerId");

                    b.Property<int>("UnitId");

                    b.Property<DateTime>("UpdatdAt");

                    b.HasKey("AssignmentId");

                    b.HasIndex("RiderAssignedRescuerId");

                    b.HasIndex("UnitId");

                    b.ToTable("Assignment");
                });

            modelBuilder.Entity("Dispatch.Models.Dispatch", b =>
                {
                    b.Property<int>("DispatchId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("IncidentId");

                    b.Property<int>("UnitId");

                    b.Property<DateTime>("UpdatdAt");

                    b.HasKey("DispatchId");

                    b.HasIndex("IncidentId");

                    b.HasIndex("UnitId");

                    b.ToTable("Dispatch");
                });

            modelBuilder.Entity("Dispatch.Models.Incident", b =>
                {
                    b.Property<int>("IncidentId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<int?>("DispatcherUserId");

                    b.Property<string>("Location")
                        .IsRequired();

                    b.Property<string>("Type")
                        .IsRequired();

                    b.Property<DateTime>("UpdatdAt");

                    b.HasKey("IncidentId");

                    b.HasIndex("DispatcherUserId");

                    b.ToTable("Incident");
                });

            modelBuilder.Entity("Dispatch.Models.Rescuer", b =>
                {
                    b.Property<int>("RescuerId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<int?>("AssignedUnitUnitId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Rank");

                    b.Property<DateTime>("UpdatdAt");

                    b.HasKey("RescuerId");

                    b.HasIndex("AssignedUnitUnitId");

                    b.ToTable("Rescuer");
                });

            modelBuilder.Entity("Dispatch.Models.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Number");

                    b.Property<string>("UnitType");

                    b.Property<DateTime>("UpdatdAt");

                    b.HasKey("UnitId");

                    b.ToTable("Unit");
                });

            modelBuilder.Entity("Dispatch.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Dispatch.Models.Assignment", b =>
                {
                    b.HasOne("Dispatch.Models.Rescuer", "RiderAssigned")
                        .WithMany()
                        .HasForeignKey("RiderAssignedRescuerId");

                    b.HasOne("Dispatch.Models.Unit", "UnitAssigned")
                        .WithMany("personnel")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dispatch.Models.Dispatch", b =>
                {
                    b.HasOne("Dispatch.Models.Incident", "DispatchedIncident")
                        .WithMany("dispatchedUnits")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dispatch.Models.Unit", "UnitDispatched")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dispatch.Models.Incident", b =>
                {
                    b.HasOne("Dispatch.Models.User", "Dispatcher")
                        .WithMany("IncidentsDispatched")
                        .HasForeignKey("DispatcherUserId");
                });

            modelBuilder.Entity("Dispatch.Models.Rescuer", b =>
                {
                    b.HasOne("Dispatch.Models.Unit", "AssignedUnit")
                        .WithMany()
                        .HasForeignKey("AssignedUnitUnitId");
                });
#pragma warning restore 612, 618
        }
    }
}
